version: '3.1'

services:

  #SERVICIO DE BASE DE DATOS ========================
  db:
    image: mysql
    container_name: db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./api/data:/var/lib/mysql
    networks:
      - my_network
    ports:
      - 5055:3306

  adminer:
    image: adminer
    restart: always
    networks:
      - my_network
    ports:
      - 8080:8080

  #SERVICIO DE BACKEND ==============================
  backend:
    image: jpanaza/backend_ace2p2_g2:latest
    container_name: backend
    privileged: true
    restart: always
    networks:
      - my_network
    ports:
      - 8000:8000
    depends_on:
      - db
  
  #SERVICIO DE FRONTEND ==============================
  frontend:
    image: jpanaza/frontend_ace2p2_g2:1.0.0
    container_name: frontend
    restart: always
    networks:
      - my_network
    ports:
      - 3000:80
    depends_on:
      - backend
networks:
  my_network:
volumes:
  volume_mysql: