version: '3.1'

services:

  #SERVICIO DE BASE DE DATOS ========================
  db:
    image: mysql
    container_name: db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my_network
    ports:
      - 3310:3306

  adminer:
    image: adminer
    restart: always
    networks:
      - my_network
    ports:
      - 8081:8080
networks:
  my_network:
volumes:
  volume_mysql: